#!/bin/bash
qemu-img create -f qcow2 alpine.img 10G
#qemu-img resize alpine.img +5G

# I N S T A L L
qemu-system-aarch64 \
	-machine virt \
	-m 1024 \
	-smp cpus=2 \
	-cpu cortex-a57 \
	-drive if=pflash,format=raw,read-only=on,file=$PREFIX/share/qemu/edk2-aarch64-code.fd \
	-drive file=alpine.img,format=qcow2,if=virtio \
	-device virtio-gpu-pci \
	-cdrom alpine-standard-3.21.3-aarch64.iso \
	-vnc :0

# R U N
qemu-system-aarch64 \
	-machine virt \
	-m 1024 \
	-smp cpus=2 \
	-cpu cortex-a57 \
	-drive if=pflash,format=raw,read-only=on,file=$PREFIX/share/qemu/edk2-aarch64-code.fd \
	-drive file=alpine.img,format=qcow2,if=virtio \
	-netdev user,id=n1,hostfwd=tcp::2222-:22 \
	-device virtio-net,netdev=n1 \
	-nographic                           

# T A K E 2
qemu-system-aarch64 \
	-M virt \
	-m 1024 \
	-cpu cortex-a57 \
	-kernel ./netboot/boot/vmlinuz-lts \
	-append "root=/dev/vda rw console=ttyAMA0" \
	-initrd ./netboot/boot/initramfs-lts \
	-drive file=alpine.img,if=virtio \
	-netdev user,id=mynet \
	-device virtio-net-pci,netdev=mynet \
	-device virtio-gpu-pci \
	-vnc :0
# 3
qemu-system-aarch64 \
	-m 1024 \
	-cpu cortex-a57 \
	-kernel vmlinuz-lts \
	-initrd initramfs-lts \
	-append "root=/dev/vda console=ttyAMA0" \
	-hda alpine.img \
	-netdev user,id=net0,hostfwd=tcp::5901-:5901 \
	-device virtio-net-pci,netdev=net0 \
	-nographic \
	-vnc :1
# 4
qemu-system-aarch64 \
	-M virt \
	-m 512M \
	-cpu cortex-a57 \
	-kernel boot/vmlinuz-lts \
	-initrd alpine-minirootfs-3.21.3-aarch64.tar.gz \
	-append "root=/dev/ram0 console=ttyAMA0" \
	-netdev user,id=mynet0 -device virtio-net-pci,netdev=mynet0 \
	-nographic \
	-vnc :1

#5

qemu-system-aarch64 \
  -M virt \
  -m 1024 \
  -cpu cortex-a57 \
  -kernel /data/data/com.termux/files/usr/share/qemu/edk2-arm64/edk2-aarch64-code.fd \
  -append "root=/dev/vda rw console=ttyAMA0" \
  -drive file=alpine-virt-3.21.3-aarch64.iso,media=cdrom,readonly=on \
  -drive file=alpine.img,if=virtio \
  -netdev user,id=net0 -device virtio-net-pci,netdev=net0 \
  -nographic \
  -vnc :1
