#!/bin/bash
#exec chpst -u rami:rami \
sudo nsenter -t 1 -m -- \
rclone mount nextcloud: /mnt/nextcloud \
	--gid 9997 \
	--dir-perms 0771 \
	--file-perms 0660 \
	--umask=0 \
	--vfs-cache-mode full \
	--vfs-cache-max-size 10G \
	--vfs-cache-max-age 48h \
	--vfs-fast-fingerprint \
	--vfs-write-back 20s \
	--attr-timeout 20s \
	--dir-cache-time 1000h \
	--cache-chunk-size 8M \
	--buffer-size 1G \
	--no-checksum \
	--no-modtime

sudo nsenter -t 1 -m -- sshfs rami@0.0.0.0:/home/rami/Cloud /storage/emulated/0/Cloud
    -o uid=$(id -u),gid=9997 \
    -o umask=0007 \
#
    -o cache_timeout=1001 \
    -o cache_stat_timeout=20 \
    -o cache_dir_timeout=20 \
    -o cache=yes \
    -o writeback_cache \
    -o max_readahead=1048576 \
    -o idmap=user
